@startuml

abstract AbstractClass {
  abstract method1()
  abstract method2()
  abstract method3()
  templateMethod()
}

class ConcreteClass {
  method1
  method2
  method3
}

ConcreteClass -u-|> AbstractClass

@enduml
